version: '3.7'
services:
  bonapp-api:
    container_name: bonapp-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - postgres
    env_file:
      - .env

  postgres:
    image: postgres:13
    container_name: postgres-bonapp
    restart: always
    ports:
      - 5436:5436
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    name: bonapp-db
