version: '3.7'
services:
  postgres:
    image: postgres:13
    container_name: postgres-bonapp
    restart: always
    ports:
      - 5436:5436
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    name: bonapp-db
